config/routes.rb
require "specialist_publisher"

SpecialistPublisher::Application.routes.draw do
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails::Engine)
  mount GovukAdminTemplate::Engine, at: "/style-guide"
  if Rails.env.development?
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
  end

  document_types = SpecialistPublisher.document_types.map(&:pluralize)

  document_types.each do |type|
    type_slug = type.to_s.gsub("_", "-")

    resources type.to_sym, controller: type, except: :destroy, path: type_slug do
      resources :attachments, only: [:new, :create, :edit, :update]
      post :withdraw, on: :member
      post :publish, on: :member

      # This is for persisted documents
      post :preview, on: :member
    end

    # This is for new documents
    post "#{type_slug}/preview" => "abstract_documents#preview", as: "preview_new_#{type}"
  end

  # Redirect old specialist-document routes to cma-cases
  get "/specialist-documents", to: redirect("/cma-cases")
  get "/specialist-documents/(*path)", to: redirect { |params, _| "/cma-cases/#{params[:path]}" }

  resources :manuals, except: :destroy do
    resources :documents, except: :destroy, path: "sections", controller: "ManualDocuments" do
      resources :attachments, controller: :manual_document_attachments, only: [:new, :create, :edit, :update]

      # This is for persisted manual documents
      post :preview, on: :member

      get :reorder, on: :collection
      post :update_order, on: :collection
    end

    post :publish, on: :member

    # This is for persisted manuals
    post :preview, on: :member
  end

  # This is for new manualss
  post "manuals/preview" => "Manuals#preview", as: "preview_new_manual"
  # This is for new manual documents
  post "manuals/:manual_id/sections/preview" => "ManualDocuments#preview", as: "preview_new_manual_document"

  root to: redirect("/manuals")
end

app/models/specialist_document.rb
require "forwardable"
require "active_model/conversion"
require "active_model/naming"

class SpecialistDocument
  extend Forwardable

  def self.edition_attributes
    [
      :title,
      :slug,
      :summary,
      :body,
      :document_type,
      :updated_at,
      :version_number,
      :extra_fields,
      # TODO: These fields expose the edition a little too directly, rethink?
      :change_note,
      :change_history,
      :minor_update,
      :public_updated_at
    ]
  end

  def_delegators :latest_edition, *edition_attributes

  attr_reader :id, :editions, :latest_edition

  def initialize(slug_generator, id, editions, edition_factory = SpecialistDocumentEdition.method(:new))
    @slug_generator = slug_generator
    @id = id
    @editions = editions
    @edition_factory = edition_factory
    @editions.push(create_first_edition) if @editions.empty?
    @latest_edition = @editions.last
  end

  def minor_update?
    !!minor_update
  end

  def to_param
    id
  end

  def extra_fields
    latest_edition.extra_fields.symbolize_keys
  end

  def attributes
    latest_edition
      .attributes
      .symbolize_keys
      .merge(extra_fields: extra_fields)
      .select { |k, _|
        self.class.edition_attributes.include?(k)
      }
      .merge(
        id: id,
      )
  end

  def update(params)
    # TODO: this is very defensive, we need enforce consistency of params at the boudary
    params = params
      .select { |k, _| allowed_update_params.include?(k.to_s) }
      .symbolize_keys

    if never_published? && params.fetch(:title, false)
      params = params.merge(
        slug: slug_generator.call(params.fetch(:title))
      )
    end

    if draft?
      latest_edition.assign_attributes(params)
    else
      @latest_edition = new_draft(params)
      editions.push(@latest_edition)
    end

    nil
  end

  def published?
    editions.any?(&:published?)
  end

  def draft?
    latest_edition.draft?
  end

  def add_attachment(attributes)
    latest_edition.build_attachment(attributes)
  end

  def attachments
    latest_edition.attachments.to_a
  end

  def publish!
    unless latest_edition.published?
      published_edition.archive if published_edition

      latest_edition.publish
    end
  end

  def withdraw!
    published_edition.archive if published_edition
  end

  def withdrawn?
    most_recent_non_draft && most_recent_non_draft.archived?
  end

  def find_attachment_by_id(attachment_id)
    attachments.find { |a| a.id.to_s == attachment_id }
  end

  def publication_state
    if withdrawn?
      "withdrawn"
    elsif published?
      "published"
    elsif draft?
      "draft"
    end
  end

  def published_edition
    if most_recent_non_draft && most_recent_non_draft.published?
      most_recent_non_draft
    end
  end

  def needs_exporting?
    latest_edition.exported_at.nil?
  end

  def mark_as_exported_to_live_publishing_api!
    edition = latest_edition
    edition.exported_at = Time.zone.now
    edition.save
  end

  def persisted?
    editions.any?(&:persisted?)
  end

protected

  attr_reader :slug_generator, :edition_factory

  def never_published?
    !published?
  end

  def new_edition_defaults
    {
      state: "draft",
      version_number: 1,
      # TODO: Remove persistence conern
      document_id: id,
    }
  end

  def create_first_edition
    edition_factory.call(new_edition_defaults)
  end

  def new_draft(params = {})
    new_edition_attributes = previous_edition_attributes
      .merge(new_edition_defaults)
      .merge(params)
      .merge(
        version_number: current_version_number + 1,
        slug: slug,
        document_type: document_type,
        attachments: attachments,
      )

    edition_factory.call(new_edition_attributes)
  end

  def current_version_number
    latest_edition.version_number
  end

  def most_recent_non_draft
    editions.reject { |e| e.draft? }.last
  end

  def previous_edition_attributes
    latest_edition.attributes
      .except(*no_copy_attributes)
      .symbolize_keys
  end

  def allowed_update_params
    self.class.edition_attributes
      .-(unupdatable_attributes)
      .map(&:to_s)
  end

  def unupdatable_attributes
    [
      :updated_at,
      :slug,
      :version_number,
    ]
  end

  def no_copy_attributes
    %w[
      _id
      created_at
      updated_at
      exported_at
    ]
  end
end

app/views/specialist_documents/_attachments_form.html.erb
<div class="col-md-4">
  <%= render partial: 'shared/govspeak-help' %>

  <% if action_name != 'update' %>
    <h2>Attachments</h2>

    <% if document.persisted? %>
      <%= link_to "Add attachment", new_specialist_document_attachment_path(document) %>
    <% else %>
      <p>To add an attachment, please save the draft first.</p>
    <% end %>

    <ul class="attachments">
      <% document.attachments.each do |attachment| %>
        <li class="attachment">
          <span class="title"><%= attachment.title %></span>
          <span class="snippet"><%= attachment.snippet %></span>
          <%= link_to "edit", edit_specialist_document_attachment_path(document, attachment) %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/specialist_documents/_js_preview.html.erb
<%= content_for :document_ready do %>
  window.SpecialistDocument.addPreviewFeature({
    'url'             : '<%= preview_path_for_specialist_document(document) %>',
    'insert_into'     : '.preview_container',
    'insert_button'   : '.preview_button',
    'render_to'       : '.preview .govspeak',
    'data_target'     : function() {
                          return {
                            '<%= form_namespace %>' : {
                              'body' : $('#<%= form_namespace %>_body').val()
                            }
                          };
                        }
  });
<% end -%>

app/views/specialist_documents/_minor_major_update_fields.html.erb
<% if document.published? %>
  <div class="checkbox add-vertical-margins">
    <%= f.check_box :minor_update,
      note: {
        text: "Only use for minor changes like fixes to typos, links, GOV.UK style or metadata.",
        class: "help-block"
      }
    %>
  </div>
  <%= f.text_area :change_note, class: 'form-control short-textarea' %>
<% end %>

app/views/specialist_documents/_publish_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Publish document</h3>
  </div>
  <div class="panel-body">
    <% if warning %>
      <strong>
        <%= warning.html_safe %>
      </strong>
    <% end %>
    <p <% if disabled %>class="remove-bottom-margin"<% end %>>
      <%= notification.html_safe %>
    </p>
    <% unless disabled %>
      <%= form_tag([:publish, document], method: :post) do %>
        <button name="submit" class="btn btn-danger" data-module="confirm" data-message="<%= strip_tags(notification.html_safe) %> Continue?">Publish</button>
      <% end %>
    <% end %>
  </div>
</div>

app/views/specialist_documents/_search.html.erb
<%= form_tag(specialist_documents_path(document_type), method: :get, class: "add-vertical-margins well") do %>
  <%= label_tag "query", "Search" %>
  <%= text_field_tag("query", params[:query], class: "form-control add-bottom-margin") %>
  <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
<% end %>

app/views/specialist_documents/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your documents", specialist_documents_path(resource_name) %></li>
  <li><%= link_to document.title, specialist_document_path(document) %></li>
  <li class='active'>Edit document</li>
<% end %>

<h1 class="page-header">Edit document</h1>

<div class="row">
<%= render partial: "#{resource_name}/form", locals: { document: document } %>
</div>

app/views/specialist_documents/index.html.erb
<% content_for :breadcrumbs do %>
  <li class='active'>Your documents</li>
<% end %>

<h1 class="page-header">Your documents</h1>

<div class="row">
  <div class="sidebar col-md-3">
    <%= link_to "New document", new_specialist_document_path(document_type), class: 'action-link' %>

    <%= render 'specialist_documents/search' %>
  </div>
  <div class="col-md-9">
    <ul class="document-list">
      <% documents.each do |document| %>
        <li class="document">
          <%= link_to document.title, specialist_document_path(document), class: 'document-title' %>
          <ul class="metadata">
            <li class="text-muted">Updated <%= time_ago_in_words(document.updated_at) %> ago</li>
            <li>
              <%= state(document) %>
            </li>
          </ul>
        </li>
      <% end %>
    </ul>
    <%= paginate documents %>
  </div>
</div>

app/views/specialist_documents/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your documents", specialist_documents_path(document_type) %></li>
  <li class='active'>New document</li>
<% end %>

<h1 class="page-header">New document</h1>

<div class="row">
<%= render partial: "#{document_type.pluralize}/form", locals: { document: document } %>
</div>

app/views/specialist_documents/show.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your documents", specialist_documents_path(resource_name) %></li>
  <li class='active'><%= document.title %></li>
<% end %>

<%= render partial: "shared/title", locals: { document: document, public_url: published_specialist_document_path(document) } %>

<div class="row">
  <div class="col-md-8">
    <h2>Summary</h2>
    <p class="lead"><%= document.summary %></p>
  </div>
</div>
<div class="row add-bottom-margin">
  <div class=" col-md-8">
    <h2>Metadata</h2>
    <dl class="metadata-list">
      <% document.humanized_attributes.each_pair do |label, values| %>
        <dt><%= label.to_s.humanize %></dt>
        <% if values.is_a?(Time) %>
          <dd><time><%= values.to_s(:govuk_date) %></time></dd>
        <% else %>
          <% Array(values).each do |value| %>
            <dd><%= truncate(value.to_s, length: 140) %></dd>
          <% end %>
        <% end %>
      <% end %>
      <dt>Publication state</dt>
      <dd><%= state(document) %></dd>
    </dl>
  </div>
</div>

<% if document.body.present? %>
  <div class="row">
    <div class="col-md-8">
      <h2>Body</h2>
      <pre class="body-pre add-bottom-margin"><%= document.body %></pre>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-8">
    <%
      truncate_at_size = 5
      attachments = document.attachments
    %>
    <h2 class="add-bottom-margin">
      <%= number_with_delimiter(attachments.size) %> <%= 'attachment'.pluralize(attachments.size) %>
    </h2>
    <% if document.attachments.any? %>
      <table class="table table-bordered table-striped add-bottom-margin" data-module="toggle">
        <thead>
          <tr class="table-header">
            <th>Title</th>
            <th>Created</th>
            <th>Last&nbsp;updated</th>
          </tr>
        </thead>
        <% attachments.each_with_index do | attachment, i | %>
          <% if i == truncate_at_size - 1 %>
            <tr class="table-header">
              <td colspan="3" class="js-toggle-target text-center">
                <strong><a href="#expand-table" class="js-toggle">…and <%= attachments.size - (truncate_at_size - 1)%> more</a></strong>
              </td>
            </tr>
          <% end %>
          <tr <% if i > truncate_at_size - 2 %>class="js-toggle-target if-js-hide"<% end %>>
            <td><%= attachment.title %></td>
            <td><%= attachment.created_at.to_date.to_s(:govuk_date) %></td>
            <td><%= attachment.updated_at.to_date.to_s(:govuk_date) %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <p class='no-content-message'>This document doesn’t have any attachments</p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h2>Actions</h2>
    <div class="well">
      <%= link_to "Edit document", [:edit, document], class: "btn btn-success" %>
    </div>

    <%= publish_form(slug_unique, publishable, document) %>

    <% if current_user_can_withdraw?(document.document_type) %>
      <%= form_tag([:withdraw, document], method: :post, class: 'panel panel-default') do %>
        <div class="panel-heading">
          <div class="panel-title">
            Withdraw document
          </div>
        </div>
        <div class="panel-body">
          <p>The document will be removed from the site. It will still be possible to edit the document and publish a new version.</p>
          <button name="submit" class="btn btn-warning" data-module="confirm" data-message="Are you sure you want to withdraw this document?">Withdraw document</button>
        </div>
      <% end %>
    <% end %>
  </div>
</div>