config/routes.rb
require "specialist_publisher"

SpecialistPublisher::Application.routes.draw do
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails::Engine)
  mount GovukAdminTemplate::Engine, at: "/style-guide"
  if Rails.env.development?
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
  end

  document_types = SpecialistPublisher.document_types.map(&:pluralize)

  document_types.each do |type|
    type_slug = type.to_s.gsub("_", "-")

    resources type.to_sym, controller: type, except: :destroy, path: type_slug do
      resources :attachments, only: [:new, :create, :edit, :update]
      post :withdraw, on: :member
      post :publish, on: :member

      # This is for persisted documents
      post :preview, on: :member
    end

    # This is for new documents
    post "#{type_slug}/preview" => "abstract_documents#preview", as: "preview_new_#{type}"
  end

  # Redirect old specialist-document routes to cma-cases
  get "/specialist-documents", to: redirect("/cma-cases")
  get "/specialist-documents/(*path)", to: redirect { |params, _| "/cma-cases/#{params[:path]}" }

  resources :manuals, except: :destroy do
    resources :documents, except: :destroy, path: "sections", controller: "ManualDocuments" do
      resources :attachments, controller: :manual_document_attachments, only: [:new, :create, :edit, :update]

      # This is for persisted manual documents
      post :preview, on: :member

      get :reorder, on: :collection
      post :update_order, on: :collection
    end

    post :publish, on: :member

    # This is for persisted manuals
    post :preview, on: :member
  end

  # This is for new manualss
  post "manuals/preview" => "Manuals#preview", as: "preview_new_manual"
  # This is for new manual documents
  post "manuals/:manual_id/sections/preview" => "ManualDocuments#preview", as: "preview_new_manual_document"

  root to: redirect("/manuals")
end

app/models/attachment.rb
require "attachable"

class Attachment
  include Mongoid::Document
  include Mongoid::Timestamps
  include Attachable

  field :title
  field :filename
  attaches :file, with_url_field: true, update_existing: true

  embedded_in :specialist_document_edition

  def to_param
    id
  end

  def snippet
    "[InlineAttachment:#{filename}]"
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  def new
    document, attachment = services.new(document_id).call

    render("attachments/new", locals: {
      document: view_adapter(document),
      attachment: attachment,
    })
  end

  def create
    document, attachment = services.create(self, document_id).call

    redirect_to(edit_path(document))
  end

  def edit
    document, attachment = services.show(self, document_id).call

    render("attachments/edit", locals: {
      document: view_adapter(document),
      attachment: attachment,
    })
  end

  def update
    document, attachment = services.update(self, document_id).call

    if attachment.persisted?
      redirect_to(edit_path(document))
    else
      render("attachments/edit", locals: {
        document: view_adapter(document),
        attachment: attachment,
      })
    end
  end

private
  def view_adapter(document)
    SpecialistPublisher.view_adapter(document)
  end

  def services
    SpecialistPublisher.attachment_services(document_type)
  end

  def edit_path(document)
    send("edit_#{document_type}_path", document)
  end

  def document_id
    params
      .select { |k, _v| k.ends_with?("_id") }
      .values
      .fetch(0)
  end

  def document_type
    params
      .select { |k, _v| k.ends_with?("_id") }
      .keys
      .fetch(0)
      .sub(/_id\z/, "")
  end
end

app/views/attachments/_breadcrumbs.html.erb
<% content_for :breadcrumbs do %>
  <% if document.document_type == 'cma_case' %>
    <li><%= link_to "Your documents", cma_cases_path %></li>
    <li><%= link_to document.title, cma_case_path(document) %></li>
  <% elsif document.document_type == 'aaib_report' %>
    <li><%= link_to "Your documents", aaib_reports_path %></li>
    <li><%= link_to document.title, aaib_report_path(document) %></li>
  <% end %>
  <li class='active'>Edit attachment</li>
<% end %>

app/views/attachments/_form.html.erb
<%= form_for([document, attachment]) do |f| %>
  <%= f.text_field :title, class: 'form-control input-md-8' %>
  <%= f.file_field :file %>
  <div class='actions'>
    <button type="submit" class='btn btn-success'>Save attachment</button>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<%= render partial: "attachments/breadcrumbs", locals: { document: document } %>

<h1 class="page-header">Edit attachment</h1>

<%= render(partial: "attachments/form", locals: {
  document: document,
  attachment: attachment,
}) %>

app/views/attachments/new.html.erb
<%= render partial: "attachments/breadcrumbs", locals: { document: document } %>

<h1 class="page-header">Add attachment</h1>

<%= render(partial: "attachments/form", locals: {
  document: document,
  attachment: attachment,
}) %>