config/routes.rb
require "specialist_publisher"

SpecialistPublisher::Application.routes.draw do
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails::Engine)
  mount GovukAdminTemplate::Engine, at: "/style-guide"
  if Rails.env.development?
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
  end

  document_types = SpecialistPublisher.document_types.map(&:pluralize)

  document_types.each do |type|
    type_slug = type.to_s.gsub("_", "-")

    resources type.to_sym, controller: type, except: :destroy, path: type_slug do
      resources :attachments, only: [:new, :create, :edit, :update]
      post :withdraw, on: :member
      post :publish, on: :member

      # This is for persisted documents
      post :preview, on: :member
    end

    # This is for new documents
    post "#{type_slug}/preview" => "abstract_documents#preview", as: "preview_new_#{type}"
  end

  # Redirect old specialist-document routes to cma-cases
  get "/specialist-documents", to: redirect("/cma-cases")
  get "/specialist-documents/(*path)", to: redirect { |params, _| "/cma-cases/#{params[:path]}" }

  resources :manuals, except: :destroy do
    resources :documents, except: :destroy, path: "sections", controller: "ManualDocuments" do
      resources :attachments, controller: :manual_document_attachments, only: [:new, :create, :edit, :update]

      # This is for persisted manual documents
      post :preview, on: :member

      get :reorder, on: :collection
      post :update_order, on: :collection
    end

    post :publish, on: :member

    # This is for persisted manuals
    post :preview, on: :member
  end

  # This is for new manualss
  post "manuals/preview" => "Manuals#preview", as: "preview_new_manual"
  # This is for new manual documents
  post "manuals/:manual_id/sections/preview" => "ManualDocuments#preview", as: "preview_new_manual_document"

  root to: redirect("/manuals")
end

app/controllers/manual_document_attachments_controller.rb
class ManualDocumentAttachmentsController < ApplicationController
  def new
    manual, document, attachment = services.new(self).call

    render(:new, locals: {
      manual: ManualViewAdapter.new(manual),
      document: ManualDocumentViewAdapter.new(manual, document),
      attachment: attachment,
    })
  end

  def create
    manual, document, attachment = services.create(self).call

    redirect_to edit_manual_document_path(manual, document)
  end

  def edit
    manual, document, attachment = services.show(self).call

    render(:edit, locals: {
      manual: ManualViewAdapter.new(manual),
      document: ManualDocumentViewAdapter.new(manual, document),
      attachment: attachment,
    })
  end

  def update
    manual, document, attachment = services.update(self).call

    if attachment.persisted?
      redirect_to(edit_manual_document_path(manual, document))
    else
      render(:edit, locals: {
        manual: ManualViewAdapter.new(manual),
        document: ManualDocumentViewAdapter.new(manual, document),
        attachment: attachment,
      })
    end
  end

private
  def services
    if current_user_is_gds_editor?
      gds_editor_services
    else
      organisational_services
    end
  end

  def gds_editor_services
    ManualDocumentAttachmentServiceRegistry.new
  end

  def organisational_services
    OrganisationalManualDocumentAttachmentServiceRegistry.new(
      organisation_slug: current_organisation_slug,
    )
  end
end

app/views/manual_document_attachments/_form.html.erb
<%= form_for([manual, document, attachment]) do |f| %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.file_field :file %>
  <div class='actions'>
    <button type="submit" class="btn btn-success">Save attachment</button>
  </div>
<% end %>

app/views/manual_document_attachments/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your manuals", manuals_path %></li>
  <li><%= link_to manual.title, manual_path(manual) %></li>
  <li><%= link_to document.title, manual_document_path(manual, document) %></li>
  <li class='active'>Edit attachment</li>
<% end %>

<h1 class="page-header">Edit attachment</h1>

<%= render(partial: "form", locals: {
  manual: manual,
  document: document,
  attachment: attachment,
}) %>

app/views/manual_document_attachments/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your manuals", manuals_path %></li>
  <li><%= link_to manual.title, manual_path(manual) %></li>
  <li><%= link_to document.title, manual_document_path(manual, document) %></li>
  <li class='active'>Add attachment</li>
<% end %>

<h1 class="page-header">Add attachment</h1>

<%= render(partial: "form", locals: {
  manual: manual,
  document: document,
  attachment: attachment,
}) %>