config/routes.rb
require "specialist_publisher"

SpecialistPublisher::Application.routes.draw do
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails::Engine)
  mount GovukAdminTemplate::Engine, at: "/style-guide"
  if Rails.env.development?
    require "sidekiq/web"
    mount Sidekiq::Web => "/sidekiq"
  end

  document_types = SpecialistPublisher.document_types.map(&:pluralize)

  document_types.each do |type|
    type_slug = type.to_s.gsub("_", "-")

    resources type.to_sym, controller: type, except: :destroy, path: type_slug do
      resources :attachments, only: [:new, :create, :edit, :update]
      post :withdraw, on: :member
      post :publish, on: :member

      # This is for persisted documents
      post :preview, on: :member
    end

    # This is for new documents
    post "#{type_slug}/preview" => "abstract_documents#preview", as: "preview_new_#{type}"
  end

  # Redirect old specialist-document routes to cma-cases
  get "/specialist-documents", to: redirect("/cma-cases")
  get "/specialist-documents/(*path)", to: redirect { |params, _| "/cma-cases/#{params[:path]}" }

  resources :manuals, except: :destroy do
    resources :documents, except: :destroy, path: "sections", controller: "ManualDocuments" do
      resources :attachments, controller: :manual_document_attachments, only: [:new, :create, :edit, :update]

      # This is for persisted manual documents
      post :preview, on: :member

      get :reorder, on: :collection
      post :update_order, on: :collection
    end

    post :publish, on: :member

    # This is for persisted manuals
    post :preview, on: :member
  end

  # This is for new manualss
  post "manuals/preview" => "Manuals#preview", as: "preview_new_manual"
  # This is for new manual documents
  post "manuals/:manual_id/sections/preview" => "ManualDocuments#preview", as: "preview_new_manual_document"

  root to: redirect("/manuals")
end

app/controllers/manual_documents_controller.rb
class ManualDocumentsController < ApplicationController
  def show
    manual, document = services.show(self).call

    render(:show, locals: {
      manual: manual,
      document: document,
    })
  end

  def new
    manual, document = services.new(self).call

    render(:new, locals: {
      manual: ManualViewAdapter.new(manual),
      document: ManualDocumentViewAdapter.new(manual, document)
    })
  end

  def create
    manual, document = services.create(self).call

    if document.valid?
      redirect_to(manual_path(manual))
    else
      render(:new, locals: {
        manual: ManualViewAdapter.new(manual),
        document: ManualDocumentViewAdapter.new(manual, document),
      })
    end
  end

  def edit
    manual, document = services.show(self).call

    render(:edit, locals: {
      manual: ManualViewAdapter.new(manual),
      document: ManualDocumentViewAdapter.new(manual, document),
    })
  end

  def update
    manual, document = services.update(self).call

    if document.valid?
      redirect_to(manual_path(manual))
    else
      render(:edit, locals: {
        manual: ManualViewAdapter.new(manual),
        document: ManualDocumentViewAdapter.new(manual, document),
      })
    end
  end

  def preview
    document = services.preview(self).call

    document.valid? # Force validation check or errors will be empty

    if document.errors[:body].nil?
      render json: { preview_html: document.body }
    else
      render json: {
        preview_html: render_to_string(
          "shared/_preview_errors",
          layout: false,
          locals: {
            errors: document.errors[:body]
          }
        )
      }
    end
  end

  def reorder
    manual, documents = services.list(self).call

    render(:reorder, locals: {
      manual: ManualViewAdapter.new(manual),
      documents: documents,
    })
  end

  def update_order
    manual, documents = services.update_order(self).call

    redirect_to(
      manual_path(manual),
      flash: {
        notice: "Order of sections saved for #{manual.title}",
      },
    )
  end

private
  def services
    if current_user_is_gds_editor?
      gds_editor_services
    else
      organisational_services
    end
  end

  def gds_editor_services
    ManualDocumentServiceRegistry.new
  end

  def organisational_services
    OrganisationalManualDocumentServiceRegistry.new(
      organisation_slug: current_organisation_slug,
    )
  end
end

app/views/manual_documents/_form.html.erb
<div class='row'>
  <div class="col-md-8">
  <%= form_for [manual, document] do |f| %>
    <%= render partial: "shared/form_errors", locals: { object: document } %>

    <%= f.text_field :title, label: 'Section title', class: 'form-control' %>
    <%= f.text_area :summary, label: 'Section summary', class: 'form-control short-textarea js-length-counter', data: { :"count-message-threshold" => 280, :"count-message-selector" => ".summary-length-info" } %>
    <div class="summary-length-info warning" aria-live="polite">Summary text should be 280 characters or fewer. <span class="count"></span></div>
    <%= f.text_area :body, label: 'Section body', class: 'form-control' %>

    <div class="preview_button add-vertical-margins"></div>
    <div class="preview_container add-vertical-margins" style="display: none;"></div>

    <% if manual.published? %>
      <div class="checkbox add-vertical-margins">
        <%= f.check_box :minor_update %>
      </div>
      <%= f.text_area :change_note, class: 'form-control short-textarea' %>
    <% end %>

    <div class="actions">
      <button name='draft' class="btn btn-success">Save as draft</button>
    </div>
  <% end %>
</div>

<div class="col-md-4">

<% content_for :format_specific_help do %>
  <h3><a data-toggle="collapse" data-target="#govspeak-collapsible">Collapsible</a></h3>
  <div class="collapse" id="govspeak-collapsible">
    <pre>## Section title
body content to be collapsed.</pre>
  </div>
<% end %>

  <%= render partial: 'shared/govspeak-help' %>

  <h2>Attachments</h2>

  <% if document.persisted? %>
    <%= link_to "Add attachment", new_manual_document_attachment_path(manual, document) %>
  <% else %>
    <p>To add an attachment, please save the draft first.</p>
  <% end %>

  <ul class="attachments">
    <% document.attachments.each do |attachment| %>
      <li class="attachment">
        <span class="title"><%= attachment.title %></span>
        <span class="snippet"><%= attachment.snippet %></span>
        <%= link_to "edit", edit_manual_document_attachment_path(manual, document, attachment) %>
      </li>
    <% end %>
  </ul>
</div>
</div>
<%= content_for :document_ready do %>
  window.SpecialistDocument.addPreviewFeature({
    'url'             : '<%= preview_path_for_manual_document(manual, document) %>',
    'insert_into'     : '.preview_container',
    'insert_button'   : '.preview_button',
    'render_to'       : '.preview .govspeak',
    'data_target'     : function() {
                          return {
                            'document' : {
                              'body' : $('#document_body').val()
                            }
                          };
                        }
  });

  window.toggleHideWithCheckBox({
    $checkBox: $("#document_minor_update"),
    $elementToHide: $("#document_change_note").parent()
  });

<% end -%>

app/views/manual_documents/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your manuals", manuals_path %></li>
  <li><%= link_to manual.title, manual_path(manual) %></li>
  <li><%= link_to document.title, manual_document_path(manual, document) %></li>
  <li class='active'>Edit section</li>
<% end %>

<h1 class="page-header">Edit section</h1>

<%= render partial: "form", locals: { document: document, manual: manual} %>

app/views/manual_documents/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your manuals", manuals_path %></li>
  <li><%= link_to manual.title, manual_path(manual) %></li>
  <li class='active'>Add section</li>
<% end %>

<h1 class='page-header'>Add section</h1>

<%= render "form", manual: manual, document: document %>

app/views/manual_documents/reorder.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your manuals", manuals_path %></li>
  <li><%= link_to manual.title, manual_path(manual) %></li>
  <li class="active">Reorder sections</li>
<% end %>

<h1 class="page-header">
  Reorder sections
</h1>
<%= form_tag(update_order_manual_documents_path(manual), method: :post) do %>
  <div class="row">
    <div class="col-md-8">
      <ol class="reorderable-document-list">
        <% documents.each do |document| %>
          <li>
            <input type="hidden" name="section_order[]" value="<%= document.id %>">
            <%= document.title %>
          </li>
        <% end %>
      </ol>
    </div>
  </div>

  <div class="actions">
    <button name="submit" class="btn btn-primary">Save section order</button>
    <%= link_to "Back", manual_path(manual), class: "action-link" %>
  </div>
<% end %>

app/views/manual_documents/show.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "Your manuals", manuals_path %></li>
  <li><%= link_to manual.title, manual_path(manual) %></li>
  <li class='active'><%= document.title %></li>
<% end %>

<h1 class="page-header">
  <%= document.title %>
</h1>

<div class="row">
  <div class="sidebar col-md-8">
    <h2>Summary</h2>
    <p><%= document.summary %></p>
  </div>
</div>

<div class="actions">
  <%= link_to("Edit section", edit_manual_document_path(manual, document), class: 'action-link') %>
</div>